### PR TITLE
Add entity review

### PR DESCRIPTION
**Pull request by stangthanin**
(User)  1<--->N  (Review)  N<--->1  (Session)

(User)  N<--->N (Review.reportByUser)

### CODE REVIEW

**Review by saenyakorn — COMMENTED** [review]
I'm really not sure about this. @saengowp help

**Comment by saengowp** [comment]
Sorry, didn't see the mention. 

I can attest that these entities is good because I've stolen this from @ThanatPhr

**Review by saengowp — APPROVED** [review]

**Comment by saengowp** [comment]
Wait. Is `Session.creator` always the same `Session.service.expert`?

**Comment by saengowp** [comment]
I spent 4 hour doing a failed git surgery to get this demo up, pls review

Demo: https://dev.choco.saenyakorn.dev/expert/pipat

**Pull request closed without merging**
