### PR TITLE
Search and display expert requests by username and display name.

### PR DESCRIPTION
**Pull request by Thanapoom02281**

### CODE REVIEW

**Review by PoraRee — APPROVED** [review]
LGTM

**Review by saenyakorn — COMMENTED** [review]
What if user change  his/her firstname or lastname after applying for an expert?

**Comment by Thanapoom02281** [comment]
> What if user change his/her firstname or lastname after applying for an expert?

The username and displayname will remain the same, but Firstname and Lastname will be shown in the next page

**Comment by saenyakorn** [comment]
I think we have no need to store `firstname` `lastname` or even `displayname` in this entity. Just store `username` and `expert_applicatiton_id`

To search with displayname you can do something like this

```
SELECT * 
FROM user JOIN expert_app
WHERE displayname LIKE '%{keyword}%'
```

// like you did before

**Comment by Thanapoom02281** [comment]
> I think we have no need to store `firstname` `lastname` or even `displayname` in this entity. Just store `username` and `expert_applicatiton_id`
> 
> To search with displayname you can do something like this
> 
> ```
> SELECT * 
> FROM user JOIN expert_app
> WHERE displayname LIKE '%{keyword}%'
> ```
> 
> // like you did before

I show the display name as well

**Comment by saenyakorn** [comment]
Then 
```sql
SELECT u.username, u.displayname
FROM user u JOIN expert_app ea
WHERE displayname LIKE '%{keyword}%'
```
?

**Comment by saenyakorn** [comment]
Every users have thier own `displayName` (required field when registering)

**Pull request merged**
